/**
 * The 193 UN members + the 2 observer states (Vatican, Palestine).
 * Rows are ordered by familiarity *within each continent* (for a Spanish
 * speaker), which is the teaching order of the Beat Tour.
 *
 * difficulty: 1 famous, 2 known, 3 rare.
 * decoys: famous cities that are NOT the capital (Capitales traps).
 * capital: null = excluded from Capitales (disputed status).
 */
export type ContinentId = 'europa' | 'sudamerica' | 'norteamerica' | 'africa' | 'asia' | 'oceania';

export interface Country {
  id: string;
  name: string;
  capital: string | null;
  continent: ContinentId;
  difficulty: 1 | 2 | 3;
  decoys?: string[];
}

type Row = [id: string, name: string, capital: string | null, difficulty: 1 | 2 | 3, decoys?: string[]];

const ROWS: Record<ContinentId, Row[]> = {
  europa: [
    ['es', 'ESPAÑA', 'MADRID', 1, ['BARCELONA']],
    ['fr', 'FRANCIA', 'PARÍS', 1, ['MARSELLA']],
    ['it', 'ITALIA', 'ROMA', 1, ['MILÁN']],
    ['de', 'ALEMANIA', 'BERLÍN', 1, ['MÚNICH']],
    ['pt', 'PORTUGAL', 'LISBOA', 1, ['OPORTO']],
    ['gb', 'REINO UNIDO', 'LONDRES', 1, ['MÁNCHESTER']],
    ['ie', 'IRLANDA', 'DUBLÍN', 1],
    ['nl', 'PAÍSES BAJOS', 'ÁMSTERDAM', 1, ['LA HAYA', 'RÓTERDAM']],
    ['be', 'BÉLGICA', 'BRUSELAS', 1, ['AMBERES']],
    ['ch', 'SUIZA', 'BERNA', 1, ['ZÚRICH', 'GINEBRA']],
    ['gr', 'GRECIA', 'ATENAS', 1, ['SALÓNICA']],
    ['ru', 'RUSIA', 'MOSCÚ', 1, ['SAN PETERSBURGO']],
    ['at', 'AUSTRIA', 'VIENA', 1, ['SALZBURGO']],
    ['se', 'SUECIA', 'ESTOCOLMO', 2],
    ['no', 'NORUEGA', 'OSLO', 2],
    ['dk', 'DINAMARCA', 'COPENHAGUE', 2],
    ['fi', 'FINLANDIA', 'HELSINKI', 2],
    ['pl', 'POLONIA', 'VARSOVIA', 2, ['CRACOVIA']],
    ['ua', 'UCRANIA', 'KIEV', 2, ['ODESA']],
    ['cz', 'CHEQUIA', 'PRAGA', 2],
    ['hu', 'HUNGRÍA', 'BUDAPEST', 2],
    ['ro', 'RUMANÍA', 'BUCAREST', 2],
    ['hr', 'CROACIA', 'ZAGREB', 2, ['SPLIT']],
    ['is', 'ISLANDIA', 'REIKIAVIK', 2],
    ['va', 'VATICANO', 'CIUDAD DEL VATICANO', 2],
    ['mc', 'MÓNACO', 'MÓNACO', 2, ['MONTECARLO']],
    ['ad', 'ANDORRA', 'ANDORRA LA VIEJA', 2],
    ['lu', 'LUXEMBURGO', 'LUXEMBURGO', 2],
    ['mt', 'MALTA', 'LA VALETA', 2],
    ['bg', 'BULGARIA', 'SOFÍA', 2],
    ['rs', 'SERBIA', 'BELGRADO', 2],
    ['cy', 'CHIPRE', 'NICOSIA', 3, ['LIMASOL']],
    ['sk', 'ESLOVAQUIA', 'BRATISLAVA', 3],
    ['si', 'ESLOVENIA', 'LIUBLIANA', 3],
    ['ee', 'ESTONIA', 'TALLIN', 3],
    ['lv', 'LETONIA', 'RIGA', 3],
    ['lt', 'LITUANIA', 'VILNA', 3],
    ['by', 'BIELORRUSIA', 'MINSK', 3],
    ['md', 'MOLDAVIA', 'CHISINÁU', 3],
    ['ba', 'BOSNIA Y HERZEGOVINA', 'SARAJEVO', 3],
    ['me', 'MONTENEGRO', 'PODGORICA', 3],
    ['mk', 'MACEDONIA DEL NORTE', 'SKOPIE', 3],
    ['al', 'ALBANIA', 'TIRANA', 3],
    ['sm', 'SAN MARINO', 'SAN MARINO', 3],
    ['li', 'LIECHTENSTEIN', 'VADUZ', 3],
  ],
  sudamerica: [
    ['ar', 'ARGENTINA', 'BUENOS AIRES', 1, ['CÓRDOBA']],
    ['br', 'BRASIL', 'BRASILIA', 1, ['RÍO DE JANEIRO', 'SÃO PAULO']],
    ['cl', 'CHILE', 'SANTIAGO', 1, ['VALPARAÍSO']],
    ['co', 'COLOMBIA', 'BOGOTÁ', 1, ['MEDELLÍN']],
    ['pe', 'PERÚ', 'LIMA', 1, ['CUZCO']],
    ['ve', 'VENEZUELA', 'CARACAS', 2, ['MARACAIBO']],
    ['ec', 'ECUADOR', 'QUITO', 2, ['GUAYAQUIL']],
    ['uy', 'URUGUAY', 'MONTEVIDEO', 2, ['PUNTA DEL ESTE']],
    ['py', 'PARAGUAY', 'ASUNCIÓN', 2],
    ['bo', 'BOLIVIA', 'SUCRE', 2, ['SANTA CRUZ']],
    ['gy', 'GUYANA', 'GEORGETOWN', 3],
    ['sr', 'SURINAM', 'PARAMARIBO', 3],
  ],
  norteamerica: [
    ['us', 'ESTADOS UNIDOS', 'WASHINGTON', 1, ['NUEVA YORK', 'LOS ÁNGELES']],
    ['mx', 'MÉXICO', 'CIUDAD DE MÉXICO', 1, ['GUADALAJARA', 'CANCÚN']],
    ['ca', 'CANADÁ', 'OTTAWA', 1, ['TORONTO', 'MONTREAL']],
    ['cu', 'CUBA', 'LA HABANA', 1, ['SANTIAGO DE CUBA']],
    ['cr', 'COSTA RICA', 'SAN JOSÉ', 2],
    ['pa', 'PANAMÁ', 'CIUDAD DE PANAMÁ', 2],
    ['do', 'REPÚBLICA DOMINICANA', 'SANTO DOMINGO', 2, ['PUNTA CANA']],
    ['gt', 'GUATEMALA', 'CIUDAD DE GUATEMALA', 2, ['ANTIGUA']],
    ['hn', 'HONDURAS', 'TEGUCIGALPA', 2, ['SAN PEDRO SULA']],
    ['sv', 'EL SALVADOR', 'SAN SALVADOR', 2],
    ['ni', 'NICARAGUA', 'MANAGUA', 2],
    ['jm', 'JAMAICA', 'KINGSTON', 2, ['MONTEGO BAY']],
    ['ht', 'HAITÍ', 'PUERTO PRÍNCIPE', 2],
    ['bs', 'BAHAMAS', 'NASÁU', 3],
    ['bz', 'BELICE', 'BELMOPÁN', 3, ['CIUDAD DE BELICE']],
    ['tt', 'TRINIDAD Y TOBAGO', 'PUERTO ESPAÑA', 3],
    ['bb', 'BARBADOS', 'BRIDGETOWN', 3],
    ['lc', 'SANTA LUCÍA', 'CASTRIES', 3],
    ['gd', 'GRANADA', "SAINT GEORGE'S", 3],
    ['vc', 'SAN VICENTE Y LAS GRANADINAS', 'KINGSTOWN', 3],
    ['ag', 'ANTIGUA Y BARBUDA', "SAINT JOHN'S", 3],
    ['dm', 'DOMINICA', 'ROSEAU', 3],
    ['kn', 'SAN CRISTÓBAL Y NIEVES', 'BASSETERRE', 3],
  ],
  africa: [
    ['eg', 'EGIPTO', 'EL CAIRO', 1, ['ALEJANDRÍA']],
    ['ma', 'MARRUECOS', 'RABAT', 1, ['CASABLANCA', 'MARRAKECH']],
    ['za', 'SUDÁFRICA', 'PRETORIA', 1, ['JOHANNESBURGO']],
    ['ng', 'NIGERIA', 'ABUYA', 2, ['LAGOS']],
    ['ke', 'KENIA', 'NAIROBI', 2, ['MOMBASA']],
    ['et', 'ETIOPÍA', 'ADÍS ABEBA', 2],
    ['dz', 'ARGELIA', 'ARGEL', 2, ['ORÁN']],
    ['tn', 'TÚNEZ', 'TÚNEZ', 2],
    ['sn', 'SENEGAL', 'DAKAR', 2],
    ['gh', 'GHANA', 'ACRA', 2],
    ['cm', 'CAMERÚN', 'YAUNDÉ', 2, ['DUALA']],
    ['ci', 'COSTA DE MARFIL', 'YAMUSUKRO', 2, ['ABIYÁN']],
    ['tz', 'TANZANIA', 'DODOMA', 2, ['DAR ES-SALAM', 'ZANZÍBAR']],
    ['ly', 'LIBIA', 'TRÍPOLI', 2, ['BENGASI']],
    ['sd', 'SUDÁN', 'JARTUM', 2],
    ['ao', 'ANGOLA', 'LUANDA', 2],
    ['cd', 'R. D. DEL CONGO', 'KINSASA', 2, ['LUBUMBASHI']],
    ['mg', 'MADAGASCAR', 'ANTANANARIVO', 2],
    ['ug', 'UGANDA', 'KAMPALA', 2],
    ['zw', 'ZIMBABUE', 'HARARE', 3],
    ['zm', 'ZAMBIA', 'LUSAKA', 3],
    ['mz', 'MOZAMBIQUE', 'MAPUTO', 3],
    ['ml', 'MALÍ', 'BAMAKO', 3, ['TOMBUCTÚ']],
    ['ne', 'NÍGER', 'NIAMEY', 3],
    ['bf', 'BURKINA FASO', 'UAGADUGÚ', 3],
    ['td', 'CHAD', 'YAMENA', 3],
    ['so', 'SOMALIA', 'MOGADISCIO', 3],
    ['rw', 'RUANDA', 'KIGALI', 3],
    ['bi', 'BURUNDI', 'GITEGA', 3, ['BUYUMBURA']],
    ['cg', 'CONGO', 'BRAZZAVILLE', 3],
    ['ga', 'GABÓN', 'LIBREVILLE', 3],
    ['gq', 'GUINEA ECUATORIAL', 'MALABO', 3, ['BATA']],
    ['cf', 'REPÚBLICA CENTROAFRICANA', 'BANGUI', 3],
    ['ss', 'SUDÁN DEL SUR', 'YUBA', 3],
    ['er', 'ERITREA', 'ASMARA', 3],
    ['dj', 'YIBUTI', 'YIBUTI', 3],
    ['mr', 'MAURITANIA', 'NUAKCHOT', 3],
    ['gm', 'GAMBIA', 'BANJUL', 3],
    ['gn', 'GUINEA', 'CONAKRI', 3],
    ['gw', 'GUINEA-BISÁU', 'BISÁU', 3],
    ['sl', 'SIERRA LEONA', 'FREETOWN', 3],
    ['lr', 'LIBERIA', 'MONROVIA', 3],
    ['tg', 'TOGO', 'LOMÉ', 3],
    ['bj', 'BENÍN', 'PORTO NOVO', 3, ['COTONÚ']],
    ['bw', 'BOTSUANA', 'GABORONE', 3],
    ['na', 'NAMIBIA', 'WINDHOEK', 3],
    ['ls', 'LESOTO', 'MASERU', 3],
    ['sz', 'ESUATINI', 'MBABANE', 3],
    ['mw', 'MALAUI', 'LILONGÜE', 3],
    ['cv', 'CABO VERDE', 'PRAIA', 3],
    ['st', 'SANTO TOMÉ Y PRÍNCIPE', 'SANTO TOMÉ', 3],
    ['sc', 'SEYCHELLES', 'VICTORIA', 3],
    ['mu', 'MAURICIO', 'PORT LOUIS', 3],
    ['km', 'COMORAS', 'MORONI', 3],
  ],
  asia: [
    ['cn', 'CHINA', 'PEKÍN', 1, ['SHANGHÁI', 'HONG KONG']],
    ['jp', 'JAPÓN', 'TOKIO', 1, ['OSAKA', 'KIOTO']],
    ['in', 'INDIA', 'NUEVA DELHI', 1, ['BOMBAY', 'CALCUTA']],
    ['kr', 'COREA DEL SUR', 'SEÚL', 1, ['BUSÁN']],
    ['tr', 'TURQUÍA', 'ANKARA', 1, ['ESTAMBUL']],
    ['th', 'TAILANDIA', 'BANGKOK', 2, ['PHUKET']],
    ['sa', 'ARABIA SAUDÍ', 'RIAD', 2, ['LA MECA', 'YEDA']],
    ['il', 'ISRAEL', null, 2],
    ['ps', 'PALESTINA', null, 2],
    ['ir', 'IRÁN', 'TEHERÁN', 2],
    ['iq', 'IRAK', 'BAGDAD', 2, ['BASORA']],
    ['vn', 'VIETNAM', 'HANÓI', 2, ['HO CHI MINH']],
    ['id', 'INDONESIA', 'YAKARTA', 2, ['BALI']],
    ['ph', 'FILIPINAS', 'MANILA', 2],
    ['pk', 'PAKISTÁN', 'ISLAMABAD', 2, ['KARACHI', 'LAHORE']],
    ['my', 'MALASIA', 'KUALA LUMPUR', 2],
    ['sg', 'SINGAPUR', 'SINGAPUR', 2],
    ['ae', 'EMIRATOS ÁRABES UNIDOS', 'ABU DABI', 2, ['DUBÁI']],
    ['qa', 'CATAR', 'DOHA', 2],
    ['kp', 'COREA DEL NORTE', 'PIONYANG', 2],
    ['af', 'AFGANISTÁN', 'KABUL', 2],
    ['sy', 'SIRIA', 'DAMASCO', 2, ['ALEPO']],
    ['jo', 'JORDANIA', 'AMÁN', 2, ['PETRA']],
    ['lb', 'LÍBANO', 'BEIRUT', 2],
    ['kz', 'KAZAJISTÁN', 'ASTANÁ', 3, ['ALMATÝ']],
    ['uz', 'UZBEKISTÁN', 'TASKENT', 3, ['SAMARCANDA']],
    ['mn', 'MONGOLIA', 'ULÁN BATOR', 3],
    ['np', 'NEPAL', 'KATMANDÚ', 3],
    ['bd', 'BANGLADÉS', 'DACA', 3],
    ['lk', 'SRI LANKA', 'SRI JAYAWARDENAPURA KOTTE', 3, ['COLOMBO']],
    ['mm', 'BIRMANIA', 'NAIPYIDÓ', 3, ['RANGÚN']],
    ['kh', 'CAMBOYA', 'NOM PEN', 3, ['ANGKOR']],
    ['la', 'LAOS', 'VIENTIÁN', 3],
    ['bt', 'BUTÁN', 'TIMBU', 3],
    ['mv', 'MALDIVAS', 'MALÉ', 3],
    ['kw', 'KUWAIT', 'KUWAIT', 3],
    ['bh', 'BARÉIN', 'MANAMA', 3],
    ['om', 'OMÁN', 'MASCATE', 3],
    ['ye', 'YEMEN', 'SANÁ', 3, ['ADÉN']],
    ['ge', 'GEORGIA', 'TIFLIS', 3, ['BATUMI']],
    ['am', 'ARMENIA', 'EREVÁN', 3],
    ['az', 'AZERBAIYÁN', 'BAKÚ', 3],
    ['tm', 'TURKMENISTÁN', 'ASJABAD', 3],
    ['kg', 'KIRGUISTÁN', 'BISKEK', 3],
    ['tj', 'TAYIKISTÁN', 'DUSAMBÉ', 3],
    ['bn', 'BRUNÉI', 'BANDAR SERI BEGAWAN', 3],
    ['tl', 'TIMOR ORIENTAL', 'DILI', 3],
  ],
  oceania: [
    ['au', 'AUSTRALIA', 'CANBERRA', 1, ['SÍDNEY', 'MELBOURNE']],
    ['nz', 'NUEVA ZELANDA', 'WELLINGTON', 1, ['AUCKLAND']],
    ['pg', 'PAPÚA NUEVA GUINEA', 'PORT MORESBY', 2],
    ['fj', 'FIYI', 'SUVA', 2],
    ['ws', 'SAMOA', 'APIA', 3],
    ['to', 'TONGA', 'NUKUALOFA', 3],
    ['vu', 'VANUATU', 'PORT VILA', 3],
    ['sb', 'ISLAS SALOMÓN', 'HONIARA', 3],
    ['ki', 'KIRIBATI', 'TARAWA SUR', 3],
    ['fm', 'MICRONESIA', 'PALIKIR', 3],
    ['mh', 'ISLAS MARSHALL', 'MAJURO', 3],
    ['pw', 'PALAOS', 'NGERULMUD', 3],
    ['nr', 'NAURU', 'YAREN', 3],
    ['tv', 'TUVALU', 'FUNAFUTI', 3],
  ],
};

export const CONTINENTS: { id: ContinentId; name: string; color: string }[] = [
  { id: 'europa', name: 'EUROPA', color: '#4FB3FF' },
  { id: 'sudamerica', name: 'AMÉRICA DEL SUR', color: '#A7E05A' },
  { id: 'norteamerica', name: 'AMÉRICA DEL NORTE Y CARIBE', color: '#FF8C42' },
  { id: 'africa', name: 'ÁFRICA', color: '#FFD23F' },
  { id: 'asia', name: 'ASIA', color: '#FF5D8F' },
  { id: 'oceania', name: 'OCEANÍA', color: '#16C2A3' },
];

export const COUNTRIES: Country[] = CONTINENTS.flatMap(({ id: continent }) =>
  ROWS[continent].map(([id, name, capital, difficulty, decoys]) => ({ id, name, capital, continent, difficulty, decoys })),
);

/**
 * Flags people mix up. Used as preferred distractors everywhere, and as the
 * themed concerts of the final "Gira Mundial" stage.
 */
export const FLAG_CLUSTERS: { name: string; ids: string[] }[] = [
  { name: 'VERDE, BLANCO Y ROJO', ids: ['it', 'mx', 'ie', 'ci', 'in', 'ne'] },
  { name: 'AZUL, AMARILLO Y ROJO', ids: ['td', 'ro', 'ad', 'md', 'co', 've', 'ec'] },
  { name: 'ROJO Y BLANCO', ids: ['id', 'mc', 'pl', 'sg', 'at', 'lv'] },
  { name: 'LAS NÓRDICAS', ids: ['se', 'no', 'dk', 'fi', 'is'] },
  { name: 'BLANCO, AZUL Y ROJO', ids: ['ru', 'si', 'sk', 'rs', 'nl', 'lu', 'hr'] },
  { name: 'ESTRELLAS DEL SUR', ids: ['au', 'nz', 'tv', 'fj', 'ws'] },
  { name: 'VERDE, AMARILLO Y ROJO', ids: ['sn', 'ml', 'gn', 'cm', 'gh', 'bo', 'lt', 'et'] },
  { name: 'RAYAS AZULES', ids: ['hn', 'sv', 'ni', 'gt', 'ar', 'uy'] },
  { name: 'ROJO, BLANCO Y NEGRO', ids: ['iq', 'sy', 'eg', 'ye', 'jo', 'ps', 'sd', 'ae', 'kw'] },
  { name: 'MEDIAS LUNAS', ids: ['tr', 'tn', 'dz', 'pk', 'mv', 'my'] },
  { name: 'CÍRCULOS', ids: ['jp', 'bd', 'pw', 'kr', 'la'] },
  { name: 'NEGRO, ROJO Y AMARILLO', ids: ['de', 'be', 'ug', 'ht', 'li', 'cz', 'ph'] },
];

/** Capitals that sound alike or trip people up. Same roles as FLAG_CLUSTERS. */
export const CAPITAL_CLUSTERS: { name: string; ids: string[] }[] = [
  { name: 'LA FAMOSA NO ES LA CAPITAL', ids: ['au', 'ca', 'tr', 'ch', 'ma', 'us', 'br', 'nz'] },
  { name: 'MÁS TRAMPAS', ids: ['ng', 'pk', 'vn', 'kz', 'mm', 'lk', 'ci', 'tz'] },
  { name: 'CAPITAL CON NOMBRE DE PAÍS', ids: ['mx', 'gt', 'pa', 'kw', 'lu', 'mc', 'sg', 'tn', 'dj', 'sm', 'va'] },
  { name: 'SANTOS Y SANES', ids: ['cr', 'sv', 'do', 'cl', 'st', 'sm'] },
  { name: 'PUERTOS', ids: ['mu', 'pg', 'vu', 'ht', 'tt', 'bj'] },
  { name: 'LAS «-STÁN»', ids: ['af', 'pk', 'uz', 'kz', 'tm', 'kg', 'tj'] },
  { name: 'ISLAS DEL PACÍFICO', ids: ['fj', 'ws', 'to', 'sb', 'ki', 'fm', 'mh', 'pw', 'nr', 'tv'] },
  { name: 'PARECIDAS', ids: ['at', 'sk', 'si', 'hu', 'rs', 'hr', 'ba', 'me', 'mk', 'al'] },
];

export function lookalikes(clusters: { ids: string[] }[], id: string): string[] {
  const out = new Set<string>();
  for (const c of clusters) if (c.ids.includes(id)) c.ids.forEach((x) => x !== id && out.add(x));
  return [...out];
}
